// source:
// (function () {
//   if WebAuthn conditional mediation is unavailable, exit silently.
//   Find the OTP form, WebAuthn-enabled email input, and passkey error region.
//   Convert base64url strings to Uint8Array for navigator.credentials.get().
//   Convert ArrayBuffer response fields back to base64url for the server.
//   Abort conditional mediation if the user submits the OTP form.
//   POST /passkey/auth/start, run navigator.credentials.get(), then POST
//   /passkey/auth/finish with resume next/next_sig from hidden sign-in
//   inputs when present. Redirect on success. After a completed ceremony,
//   show the inline error if finish fails so the OTP form still works.
// })();

export const LANDING_JS = `(function(){if(typeof window.PublicKeyCredential!="function"||!PublicKeyCredential.isConditionalMediationAvailable)return;var l=document.querySelector('form[action="/signin/start"]'),c=document.querySelector('input[autocomplete*="webauthn"]'),o=document.getElementById("passkey-error");if(!l||!c)return;function u(){o&&(o.hidden=!1,o.textContent="passkey sign-in failed. use your email instead.")}function a(n){for(var t=new Uint8Array(n),r="",e=0;e<t.length;e++)r+=String.fromCharCode(t[e]);return btoa(r).replace(/\\+/g,"-").replace(/\\//g,"_").replace(/=+$/,"")}function s(n){for(var t=n.length%4===2?"==":n.length%4===3?"=":"",r=atob(n.replace(/-/g,"+").replace(/_/g,"/")+t),e=new Uint8Array(r.length),i=0;i<r.length;i++)e[i]=r.charCodeAt(i);return e}function d(n){return n.challenge=s(n.challenge),Array.isArray(n.allowCredentials)&&(n.allowCredentials=n.allowCredentials.map(function(t){return Object.assign({},t,{id:s(t.id)})})),n}function f(n){var t=n.response;return{id:n.id,rawId:a(n.rawId),type:n.type||"public-key",authenticatorAttachment:n.authenticatorAttachment||null,clientExtensionResults:n.getClientExtensionResults?n.getClientExtensionResults():{},response:{authenticatorData:a(t.authenticatorData),clientDataJSON:a(t.clientDataJSON),signature:a(t.signature),userHandle:t.userHandle?a(t.userHandle):null}}}function p(e){var r={response:f(e)},n=l.querySelector('input[name="next"]'),g=l.querySelector('input[name="next_sig"]');return n&&g&&n.value&&g.value&&(r.next=n.value,r.next_sig=g.value),r}PublicKeyCredential.isConditionalMediationAvailable().then(function(n){if(n){var t=new AbortController,r=!1;return l.addEventListener("submit",function(){t.abort()}),fetch("/passkey/auth/start",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:"{}"}).then(function(e){return e.ok?e.json():null}).then(function(e){return!e||!e.options?null:navigator.credentials.get({publicKey:d(e.options),mediation:"conditional",signal:t.signal})}).then(function(e){return e?(r=!0,fetch("/passkey/auth/finish",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify(p(e))})):null}).then(function(e){return e?e.ok?e.json():(u(),null):null}).then(function(e){e&&e.redirect&&(location.href=e.redirect)}).catch(function(){r&&u()})}}).catch(function(){})})();`;
