// source:
// (function () {
//   If WebAuthn is unavailable, exit silently.
//   Bind the add and skip controls in the welcome panel.
//   Convert registration options challenge, user.id, and exclude credential ids
//   from base64url to Uint8Array for navigator.credentials.create().
//   Convert attestation response fields back to base64url for the server.
//   POST /passkey/register/start, run navigator.credentials.create(), then POST
//   /passkey/register/finish with optional friendly_name. Redirect to the
//   dashboard without ?welcome=1 on success; show inline error on failure.
// })();

export const ENROLL_JS = `(function(){if(typeof window.PublicKeyCredential!="function")return;var s=document.getElementById("passkey-add"),n=document.getElementById("passkey-skip"),c=document.getElementById("passkey-friendly-name"),r=document.getElementById("passkey-enroll-error");if(!s)return;function u(){r&&(r.hidden=!1,r.textContent="couldn't add passkey. try again."),s.disabled=!1,n&&(n.disabled=!1)}function d(e){for(var t=new Uint8Array(e),a="",i=0;i<t.length;i++)a+=String.fromCharCode(t[i]);return btoa(a).replace(/\\+/g,"-").replace(/\\//g,"_").replace(/=+$/,"")}function l(e){for(var t=e.length%4===2?"==":e.length%4===3?"=":"",a=atob(e.replace(/-/g,"+").replace(/_/g,"/")+t),i=new Uint8Array(a.length),o=0;o<a.length;o++)i[o]=a.charCodeAt(o);return i}function f(e){return e.challenge=l(e.challenge),e.user.id=l(e.user.id),Array.isArray(e.excludeCredentials)&&(e.excludeCredentials=e.excludeCredentials.map(function(t){return Object.assign({},t,{id:l(t.id)})})),e}function p(e){var t=e.response;return{id:e.id,rawId:d(e.rawId),type:e.type||"public-key",authenticatorAttachment:e.authenticatorAttachment||null,clientExtensionResults:e.getClientExtensionResults?e.getClientExtensionResults():{},response:{attestationObject:d(t.attestationObject),clientDataJSON:d(t.clientDataJSON),transports:typeof t.getTransports=="function"?t.getTransports():void 0}}}n&&n.addEventListener("click",function(){location.href="/dashboard"}),s.addEventListener("click",function(){r&&(r.hidden=!0,r.textContent=""),s.disabled=!0,n&&(n.disabled=!0);var e=c?c.value.trim():"";fetch("/passkey/register/start",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:"{}"}).then(function(t){if(!t.ok)throw new Error("start");return t.json()}).then(function(t){return navigator.credentials.create({publicKey:f(t.options)})}).then(function(t){if(!t)throw new Error("empty");return fetch("/passkey/register/finish",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({response:p(t),friendly_name:e})})}).then(function(t){if(!t.ok)throw new Error("finish");location.href="/dashboard"}).catch(u)})})();`;
