name = "scouts"
account_id = "3f2c1528c7d4d9685819ea9e9e307c92"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.js"

routes = [{ pattern = "scouts.solstone.app", custom_domain = true }]

[[d1_databases]]
binding = "DB"
database_name = "scouts-portal"
database_id = "42812399-198d-4d04-af8e-f094125b5588"
migrations_dir = "migrations"

[triggers]
crons = ["0 */6 * * *"]

[[send_email]]
name = "EMAIL"
remote = true

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAADJneUy2jVC8NPC4"
EMAIL_PATH_DISABLED = "false"
