// Writes public/static/sunarc.js: the sun-arc time-of-day background for the
// marketing pages. It is the services portal's engine (account/src/sunarc.js),
// assembled the same way, with a bootstrap for these pages:
//
//   - The sunrise gradient stays the light day ground. Its layer (.ground-sunrise)
//     fades with the night weight and is off in the dark appearance.
//   - A page draws the dark row only if it opted into a dark appearance by
//     loading tokens-dark.css (computed color-scheme includes "dark"). A light-only
//     page always draws the light row, so its light content never sits on a dark
//     ground.
//
// Nothing here requests a location or makes a network call. Times come from the
// system timezone's bundled reference point. Run by `make sunarc` and `make deploy`.
import { writeFileSync } from 'node:fs';
import { SUNARC_JS } from '../account/src/sunarc.js';

const cut = SUNARC_JS.lastIndexOf('\ncreateSunarcController({');
if (cut < 0) throw new Error('sunarc bootstrap not found: the engine changed shape');

const bootstrap = `
var darkCapable = /dark/.test(window.getComputedStyle(document.documentElement).colorScheme || '');
var ctrl = createSunarcController({
  window: window,
  document: document,
  now: function() { return new Date(); },
  viewport: function() { return { w: window.innerWidth, h: window.innerHeight }; },
  getComputedStyle: function(el) { return window.getComputedStyle(el); },
  setTimeout: window.setTimeout.bind(window),
  clearTimeout: window.clearTimeout.bind(window),
  setInterval: window.setInterval.bind(window),
  clearInterval: window.clearInterval.bind(window),
  matchMedia: darkCapable && typeof window.matchMedia === 'function' ? window.matchMedia.bind(window) : null
}).start();
function sunriseGround() {
  var f = ctrl.getFrame();
  var day = f && f.appearance === 'light' ? 1 - f.time.nightAmount : 0;
  document.documentElement.style.setProperty('--sunrise-day', String(day));
}
sunriseGround();
window.setInterval(sunriseGround, 60000);
if (darkCapable && window.matchMedia) {
  var mq = window.matchMedia('(prefers-color-scheme: dark)');
  if (mq.addEventListener) mq.addEventListener('change', function() { ctrl.tick(); sunriseGround(); });
}
document.addEventListener('visibilitychange', sunriseGround);
})();`;

const out = new URL('../public/static/sunarc.js', import.meta.url);
writeFileSync(out, '// Generated by scripts/gen-sunarc.mjs from the services portal sun-arc engine. Do not hand-edit.\n' +
  SUNARC_JS.slice(0, cut) + bootstrap + '\n');
console.log('wrote public/static/sunarc.js');
